[tools]
go = "1.25.3"
node = "25.1.0"
"npm:wrangler" = "4.45.4"

[tasks]
[tasks."cloudflare:build"]
run = "go run github.com/syumai/workers/cmd/workers-assets-gen -mode=go && GOOS=js GOARCH=wasm go build -o ./build/app.wasm ./cmd/cloudflare/main.go"

[tasks."cloudflare:deploy"]
run = "wrangler deploy"

[tasks."cloudflare:dev"]
run = "wrangler dev -c ./wranger.jsonc"
